user_pref("font.default.x-western", "sans-serif");
user_pref("font.name.monospace.x-western", "Adwaita Mono");
user_pref("font.name.sans-serif.x-western", "Adwaita Sans");
user_pref("browser.search.region", "MX");
user_pref("intl.locale.requested", "es-ES,en-US");
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.warnOnQuitShortcut", false);
user_pref("signon.rememberSignons", false);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{8c5cf218-c44f-4df8-86bd-708f46b92c57}");
user_pref("zen.view.show-newtab-button-top", false);
user_pref("zen.workspaces.hide-default-container-indicator", false);
user_pref("zen.themes.disable-all", true);
user_pref("zen.ui.migration.compact-mode-button-added", true);
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("browser.urlbar.placeholderName.private", "DuckDuckGo");
user_pref("browser.urlbar.suggest.engines", false);
user_pref("privacy.userContext.enabled", false);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.formautofill.creditCards.enabled", false);
user_pref("network.trr.mode", 3);
user_pref("network.trr.uri", "https://mozilla.cloudflare-dns.com/dns-query");
